#FASTAPI-IT IS A PYTHON WEB FRAMEWORK FOR BUILDING APIs
from fastapi import FastAPI,HTTPException
#PYDANTIC-IT IS A DATA VALIDATION AND SETTINGS MANAGEMENT LIBRARY FOR PYTHON,IT PROVIDES A WAY TO DEFINE DATA MODELS AND VALIDATE THE DATA AGAINST THOSE MODELS
#IN THIS CODE,WE USE PYDANTIC TO DEFINE A MODEL FOR THE TASK DATA,WHICH INCLUDES AN ID AND A NAME. THE MODEL ENSURES THAT THE DATA SENT TO THE API ENDPOINTS IS VALID AND CONFORMS TO THE EXPECTED STRUCTURE. IT ALSO PROVIDES SERIALIZATION,ALLOWING US TO CONVERT THE DATA TO AND FROM DIFFERENT FORMATS,SUCH AS JSON,WHICH IS COMMONLY USED IN API COMMUNICATION.
#BY USING PYDANTIC,WE CAN ENSURE THAT THE DATA WE RECEIVE FROM THE CLIENT IS VALID AND CAN BE PROCESSED CORRECTLY BY THE API ENDPOINTS. IT ALSO MAKES IT EASIER TO WORK WITH THE DATA,AS WE CAN USE THE MODEL TO ACCESS THE FIELDS OF THE TASK DATA IN A STRUCTURED WAY.
#IN SUMMARY,PYDANTIC HELPS US DEFINE THE STRUCTURE AND VALIDATION OF THE DATA USED IN THE API,MAKING IT EASIER TO WORK WITH AND ENSURE DATA INTEGRITY.
from pydantic import BaseModel
#CREATE A FASTAPI INSTANCE
#APP-IT IS THE MAIN COMPONENT OF FASTAPI APPLICATION,IT HANDLES ALL THE REQUESTS AND RESPONSES
app=FastAPI()
#CREATE A MODEL FOR TASK
#BaseModel-IT IS A CLASS FROM PYDANTIC,IT PROVIDES VALIDATION AND SERIALIZATION FOR THE MODEL DATA 
#Task-IT IS A MODEL CLASS THAT INHERITS FROM BaseModel,IT DEFINES THE STRUCTURE OF THE TASK DATA WITH TWO FIELDS: id AND Name 
#id-IT IS AN INTEGER FIELD THAT REPRESENTS THE UNIQUE IDENTIFIER OF THE TASK
#Name-IT IS A STRING FIELD THAT REPRESENTS THE NAME OF THE TASK
#THE MODEL DEFINES THE STRUCTURE OF THE DATA THAT WILL BE SENT TO AND RECEIVED FROM THE API,IT ENSURES THAT THE DATA IS VALID AND CAN BE PROCESSED CORRECTLY BY THE API ENDPOINTS 
#THE MODEL ALSO PROVIDES SERIALIZATION,WHICH MEANS THAT IT CAN CONVERT THE DATA TO AND FROM DIFFERENT FORMATS,SUCH AS JSON,WHICH IS COMMONLY USED IN API COMMUNICATION
#IN SUMMARY,THE MODEL DEFINES THE STRUCTURE AND VALIDATION OF THE DATA USED IN THE API,MAKING IT EASIER TO WORK WITH AND ENSURE DATA INTEGRITY
#IN THIS CODE,THE MODEL IS USED TO DEFINE THE STRUCTURE OF THE TASK DATA,WHICH INCLUDES AN ID AND A NAME,AND IT IS USED IN THE POST AND PUT ENDPOINTS TO VALIDATE THE DATA SENT BY THE CLIENT AND ENSURE THAT IT CONFORMS TO THE EXPECTED STRUCTURE
#THE MODEL ALSO PROVIDES A WAY TO SERIALIZE THE DATA,SO THAT IT CAN BE SENT TO AND RECEIVED FROM THE API IN A FORMAT THAT IS EASY TO WORK WITH,SUCH AS JSON
#
class Task(BaseModel):
    id: int
    Name: str

#IN-MEMORY DATA STORAGE FOR TASKS
#IN THIS CODE,THE TASKS ARE STORED IN A LIST CALLED "t".EACH TASK IS REPRESENTED AS A DICTIONARY WITH AN "id" AND A "name" KEY.
#THE LIST SERVES AS A SIMPLE IN-MEMORY DATABASE FOR THE TASKS,ALLOWING US TO PERFORM CRUD (CREATE,READ,UPDATE,DELETE) OPERATIONS ON THE TASKS WITHOUT THE NEED FOR AN EXTERNAL DATABASE.HOWEVER,IT IS IMPORTANT TO NOTE THAT THIS APPROACH IS NOT PERSISTENT AND ALL DATA WILL BE LOST WHEN THE APPLICATION IS RESTARTED. 
#FOR PRODUCTION USE,IT IS RECOMMENDED TO USE A PROPER DATABASE TO STORE THE TASKS PERSISTENTLY.
#THE "tk" LIST IS USED TO STORE THE TASKS THAT HAVE BEEN RETRIEVED USING THE GET ENDPOINTS. IT SERVES AS A TEMPORARY STORAGE FOR THE TASKS THAT HAVE BEEN ACCESSED,ALLOWING US TO KEEP TRACK OF THE TASKS THAT HAVE BEEN RETRIEVED FROM THE "t" LIST.
#HOWEVER,IT IS IMPORTANT TO NOTE THAT THIS APPROACH IS NOT PERSISTENT AND ALL DATA IN THE "tk" LIST WILL BE LOST WHEN THE APPLICATION IS RESTARTED.
t=[
   {"id":1,"name":"nani"},
   {"id":2,"name":"mani"}
   ]
tk=[]

#GET,POST,PUT,DELETE METHODS IN FASTAPI
#GET-READ DATA FROM SERVER 
@app.get("/")
def home():
    return "welcome to home"
@app.get("/task")
def task():
    return t
#GET STORED TASKS
@app.get("/stored_tasks")
def get_stored_task():
    if tk:
        return tk
    raise HTTPException(status_code=404,detail="Nothing stored")
#GET TASKS BY ID AND NAME
@app.get("/tasks/{task_id}")
def get_tasks(task_id:int):
    for task in t:
        if task["id"]==task_id:
            tk.append(task)
            return task
    raise HTTPException(status_code=404,detail="Task not found")
#GET TASKS BY NAME
@app.get("/task/{task_name}")
def get_task_name(task_name:str):
    for task in t:
        if task["name"]==task_name:
            tk.append(task)
            return task
    raise HTTPException(status_code=404,detail="Task name not found")

#POST-CREATE DATA IN SERVER
@app.post("/task")
def post_task(task:dict):
    t.append(task)
    return task
#POST-CREATE DATA IN SERVER WITH MODEL VALIDATION
@app.post("/tasks")
def post_task(task:Task):
    for ta in t:
        if ta["id"]==task.id:
            raise HTTPException(status_code=404,detail="already exits")
    t.append(task)
    return task
#POST-CREATE DATA IN SERVER WITH MODEL VALIDATION AND CHECKING FOR DUPLICATE NAMES
@app.post("/tasking")
def post_tasks(task:Task):
    for ta in t:
        if ta["name"]==task.Name:
            raise HTTPException(status_code=404,detail="Task name already exists")
    t.append(task)
    return task

#PUT-UPDATE DATA IN SERVER
@app.put("/task/{id}")
def put_task(id:int,updated:Task):
    for index,task in enumerate(t):
        if task["id"]==id:
            t[index]=updated
            return updated
    raise HTTPException(status_code=404,detail="not updated")
#PUT-UPDATE DATA IN SERVER BY NAME
@app.put("/tasks/{name}")
def put_task_name(name:str,updated:Task):
    for index,task in enumerate(t):
        if task["name"]==name:
            t[index]=updated
            return updated
    raise HTTPException(status_code=404,detail="not updated")

#DELETE-DELETE DATA IN SERVER
@app.delete("/task/{id}")
def delete_task(id:int):
    for index,task in enumerate(t):
        if task["id"]==id:
            del t[index]
            return {"message":"deleted"}
    raise HTTPException(status_code=404,detail="not deleted")